name: chargee_lints
description: Recommended lints for Flutter apps, packages, and plugins created by Chargee.
version: 1.0.4
repository: https://github.com/chargee-energy/chargee_lints

environment:
  sdk: ^3.9.0

dependencies:
  flutter_lints: ">=6.0.0 < 7.0.0"
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.

topics:
  - lints
